baseURL = "https://andrewrady.github.io/"
draft = false
defaultContentLanguage = "en"
title = "Home"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
summaryLength = 30

[outputs]
  home = ["HTML", "JSON"]
